backend:
  name: git-gateway
  branch: main

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: posts
    label: Posts
    folder: src/posts/2025
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          default: [],
          allow_add: true,
          required: false,
          hint: "Add keywords to help categorize your post"
        }